name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        container: archlinux:latest

        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: pacman -Syu --noconfirm base-devel rust cargo pkgconf
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
